# Generated by Django 4.1.7 on 2023-04-07 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0010_checkout_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='product',
        ),
    ]
