# Generated by Django 4.1.7 on 2023-04-07 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0011_remove_checkout_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.product'),
        ),
    ]
