# Generated by Django 4.1.7 on 2023-04-08 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0015_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='otp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='seller',
            name='otp',
            field=models.IntegerField(default=0),
        ),
    ]
